/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Game from "./scripts/Game"
import GameStart from "./scripts/GameStart"
import Practice from "./scripts/Practice"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="showall";
    static screenMode:string="none";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="20200806.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("scripts/Game.ts",Game);
        reg("scripts/GameStart.ts",GameStart);
        reg("scripts/Practice.ts",Practice);
    }
}
GameConfig.init();